version: "3"

services:
  api:
    build: productcategory
    volumes:
      - ./productcategory:/user/src
      - gradle_cache:/home/gradle/.gradle/caches
    ports:
      - 8080:8080
    command: /bin/bash -c 'watchfile'
  front:
    build: front-crud
    ports:
      - 3000:3000
    depends_on:
      - "api"
    volumes:
      - ./front-crud:/usr/src/
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  gradle_cache: